---
title: "ANCOM-BC2 Differential Abundance"
output: html_document
date: "2025-10-23"
---
# Generate Diff Abundance Data
```{r diff_ab_ancom2}
fname <- paste0("../results/ancombc2_output_",n_asv,".rds")

if (file.exists(fname)) {
    print("loading ANCOM2 data")
    output <- readRDS(fname)
} else {
  reads <- table_abs 
  
  reads_top <- reads %>%
    filter(seq %in% seq_names) 
  
  # convert first column to row names
  rownames(reads_top) <- reads_top$seq
  reads_top <- reads_top[, -1]
  
  # make sample column row names
  smd <- metadata               # make a copy
  rownames(smd) <- smd$sample
  smd$sample <- NULL            # remove the now-redundant column
  
  output <- ancombc2(
    data = reads_top, 
    meta_data = smd,
    fix_formula = "size.mm",     # categorical factor for size classes
    rand_formula = NULL,         # independent samples
    group = "size.mm",
    struc_zero = TRUE,           # detect structural zeros
    neg_lb = TRUE,               # negative lower bound correction
    global = TRUE,               # overall test across all 6 groups
    trend = FALSE,                ## optional, if you think size classes are ordered (make size #)
    p_adj_method = "holm",       # multiple-testing correction
    alpha = 0.05
  )
  
  saveRDS(output, file = fname)
}
```
# Process Data
```{r ancom2_process}
# define significant taxa
sig_global <- output$res_global  %>%
  filter(diff_robust_abn) %>%    # use robust results (recommended)
  rename(seq = taxon,) %>%
  left_join(taxonomy, join_by(seq)) %>%
  group_by(Genus, seq, q_val, W) %>%
  summarise(.groups = "drop") %>%
  arrange(q_val)

```
# LFC plot
```{r lfc_plot}
contrast_level <- c("L", "Q", "C", "4", "5")

# log-fold change
lfc_long <- output$res %>%
  dplyr::select(taxon, dplyr::starts_with("lfc_size.mm")) %>%
  pivot_longer(
    cols = -taxon,
    names_to = "contrast",
    values_to = "lfc"
  ) %>%
  mutate(
    contrast = gsub("lfc_size.mm.", "", contrast),
    contrast = factor(contrast, levels = contrast_level)
  )

ggplot(lfc_long, aes(x = contrast, y = lfc, group = taxon, color = taxon)) +
  geom_line(alpha = 0.5) +
  theme_bw() +
  labs(
    x = "Contrast (trend component)",
    y = "Log fold-change",
    title = "Degree and shape of differential abundance across size classes"
  )
```
# BC
```{r bc}
bc_out <- output$bc_out

bc_long <- bc_out %>%
  rownames_to_column("taxon") %>%
  pivot_longer(-taxon, names_to = "sample", values_to = "bc_abund") %>%
  left_join(smd %>% rownames_to_column("sample"), by = "sample")

ggplot(bc_long %>% filter(taxon %in% sig_taxa),
       aes(x = size.mm, y = bc_abund, color = size.mm)) +
  geom_boxplot() +
  facet_wrap(~ taxon, scales = "free_y") +
  theme_bw() +
  labs(
    x = "Size class",
    y = "Bias-corrected abundance",
    title = "Differential abundance patterns across size classes"
  )

```