---
title: "16S_Visualization_main"
output:
  html_document:
    toc: yes
    df_print: paged
  html_notebook:
    theme: spacelab
    toc: yes
    toc_float: yes
---
# Data Import
```{r get_data}
# Clear environment
rm(list = ls())

# Relative Abundance Cutoff (%) used to subset high abundance taxa
rel_ab_cutoff <- 0.5 
# p-value used for filtering taxa
p_threshold   <- 0.05

# Color Palettes (MetBrewer)
size_pal <- "Java"
taxa_pal <- "Hiroshige"

source("./R/00_setup.R")
source("./R/01_load_data.R")
source("./R/02_process_ps.R")
source("./R/03_subset.R")
source("./R/04_subset_DA.R")

# ANCOM taxa
all_taxa_ancom <- get_ancom_taxa(ancom_fname, p_threshold, write2excel = FALSE)
DA_taxa <- high_ab_genera[high_ab_genera %in% all_taxa_ancom]
# Common taxa (ANCOM & ALDEx)
# DA_taxa <- get_common_taxa(ancom_fname, aldex_fname, p_threshold, effect_threshold, high_ab_genera)
```

# Correlation to Spring Pot Coefficient
```{r statistics}
source("./R/bias_correct.R")
bc_wide <- get_bc_abund(ancom_fname) %>%
  filter(Genus %in% DA_taxa) %>%
  group_by(Genus, size.name) %>%
  summarise(mean_ab = mean(bc_abund), sd_ab = sd(bc_abund)) %>%
  dplyr::select(Genus, size.name, mean_ab) %>%
  pivot_wider(
    names_from = size.name,
    values_from = mean_ab
  ) %>%
  column_to_rownames("Genus") %>%
  as.matrix()

# Correlation
corr_mu <- map_dfr(1:nrow(bc_wide), function(i) {
  res <- cor.test(bc_wide[i, ], mu, method = "spearman")
  tibble(
    Genus = rownames(bc_wide)[i],
    # correlation coefficient (+ increasing, - decreasing)
    estimate = res$estimate, 
    p.value = res$p.value
  ) %>%
  filter(p.value < p_threshold)
})

print(corr_mu)

# # Relative Abundance
# rel_wide <- get_rel_genus(ps_ASV) %>%
#   filter(Genus %in% res_df$Genus) %>%
#   group_by(Genus, size.name) %>%
#   summarise(mean_ab = mean(Abundance), sd_ab = sd(Abundance)) %>%
#   dplyr::select(Genus, size.name, mean_ab) %>%  
#   pivot_wider(
#     names_from = size.name,
#     values_from = mean_ab
#   ) %>%
#   column_to_rownames("Genus") %>%
#   as.matrix() 
```
# Correlation to EPS
```{r stats_eps}
corr_tb <- map_dfr(1:nrow(bc_wide), function(i) {
  res <- cor.test(bc_wide[i, ], eps$TB.avg, method = "spearman")
  tibble(
    Genus = rownames(bc_wide)[i],
    # correlation coefficient (+ increasing, - decreasing)
    estimate = res$estimate, 
    p.value = res$p.value
  ) %>%
  filter(p.value < p_threshold)
})

print(corr_tb)

# corr_lb <- map_dfr(1:nrow(bc_wide), function(i) {
#   res <- cor.test(bc_wide[i, ], eps$LB.avg, method = "spearman")
#   tibble(
#     Genus = rownames(bc_wide)[i],
#     # correlation coefficient (+ increasing, - decreasing)
#     estimate = res$estimate, 
#     p.value = res$p.value
#   ) %>%
#   filter(p.value < p_threshold)
# })
# 
# print(corr_lb)
```

### Plots
```{r make_plots}
source("./R/plot_ordination.R")

```
