---
title: "child_stats"
output: html_document
date: "2025-10-27"
---

```{r correlation}
merged <- as.data.frame(mu) %>%
  rownames_to_column("size.mm") %>%
  left_join(eps, join_by(size.mm)) %>%
  mutate(size.midpoint = size_midpoint)

# Named list of variable pairs
var_pairs <- list(
  TB_mu = c("TB.avg", "mu"),
  LB_mu = c("LB.avg", "mu"),
  size_mu = c("size.midpoint", "mu")
)

# One-liner to get estimates and p-values
results <- map_dfr(var_pairs, ~ cor.test(merged[[.x[1]]], merged[[.x[2]]], method = "spearman") %>%
                     broom::tidy(), .id = "comparison") %>%
  dplyr::select(comparison, estimate, p.value)

print(results)

```

# mu vs TB
```{r tb}
#mod <- lm(mu ~ TB.avg, data = merged)
ggplot(data = merged, aes(x = mu, y = TB.avg, color = size.mm)) +
  geom_point() +
  scale_color_manual(values = met.brewer(size_pal, n_sizes)) +
  #geom_smooth(method = "lm") +
  theme_minimal()
```
# PNPS
```{r eps}
eps_long <- eps %>%
  pivot_longer(
    cols = -size.mm,                              # all columns except size.mm
    names_to = c("extract.type", ".value"),        # split names into type + variable
    names_pattern = "(.*)\\.(avg|sd)"              # regex to match "LB.avg", "TB.sd", etc.
  ) %>%
  rename(
    pnps.avg = avg,
    pnps.sd  = sd
  )
ggplot(data = eps_long, aes(x = size.mm, y = pnps.avg, color = extract.type)) +
  geom_point(position = position_dodge(width = 0.2), size = 2) +
  geom_errorbar(
    aes(ymin = pnps.avg - pnps.sd, ymax = pnps.avg + pnps.sd),
    width = 0.2,
    position = position_dodge(width = 0.2)
  ) +
  scale_color_manual(values = met.brewer(taxa_pal, 2)) +
  labs(
    x = "Size [mm]",
    y = "Mean PN/PS",
    color = "Extract Type"
  ) +
  theme_minimal(base_size = 16)
print(getwd())
ggsave("../figures/PNPS.png")
```
# Moduli
```{r moduli}
ggplot(data = merged, aes(x = size.midpoint, y = mu)) +
  geom_point() +
  geom_smooth(method = "lm") +
  labs(
    x = "Size [mm]",
    y = "Mu"
  ) +
  theme_minimal()
```