---
title: "child_subset_abundance"
output: html_document
date: "2025-11-08"
---
# Define relative abundance for all High Ab Taxa
```{r all_high}
table_rel_long <- get_rel_genus(ps_ASV) %>%
  filter(Genus %in% high_ab_genera) 

rel_wide <- table_rel_long %>%
  dplyr::select(Genus, Sample, Abundance) %>%  
  pivot_wider(
    names_from = Sample,
    values_from = Abundance
  ) %>%
  column_to_rownames("Genus") %>%
  as.matrix() %>%
  # reorder columns 
  .[, sam_name]  

metadata <- data.frame(ps_ASV@sam_data) %>% .[sam_name, ] # reorder

# Define colors for size categories directly from metadata
size_colors <- setNames(met.brewer("Java", n_sizes), size$name)

# Create the annotation directly from metadata
top_annot <- HeatmapAnnotation(
  Size = factor(metadata$size.name, levels = size$name),
  col = list(Size = size_colors)
)

# Create a vector for fontface based on whether the taxon is common
row_fontface <- ifelse(rownames(rel_wide) %in% common_taxa, "bold", "plain")

```
# Plot
```{r heat_all}
# Cell height in inches (adjust as needed)
cell_h <- 0.2
cell_w <- 0.2 

# Font sizes
row_fontsize <- 10
col_fontsize <- 11

n_cols <- ncol(rel_wide)
n_rows <- nrow(rel_wide)

# Build the heatmap
ht <- Heatmap(
  rel_wide,
  name = "Rel Ab [%]",
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = FALSE,
  column_names_rot = 0,
  column_names_centered = TRUE,
  top_annotation = top_annot,
  col = colorRampPalette(brewer.pal(9, "Blues"))(100),
  # size
  width  = unit(n_cols * cell_w, "inches"),
  height = unit(n_rows * cell_h, "inches"),
  row_names_gp = gpar(fontsize = row_fontsize, fontface = row_fontface),
  column_names_gp = gpar(fontsize = col_fontsize)
)

# Save images
png("../figures/high_ab_taxa.png", 
    width = n_cols * cell_w + 4,
    height = n_rows * cell_h + 1,
    units = "in", res = 300)
draw(ht)
dev.off()

print(ht)
```

# Common Taxa Only
```{r common_taxa}

rel_common <- as.data.frame(rel_wide) %>%
  rownames_to_column(var = "Genus") %>%
  filter(Genus %in% common_taxa) %>%
  column_to_rownames(var = "Genus")
  
n_rows <- nrow(rel_common)

# Build the heatmap
ht <- Heatmap(
  rel_common,
  name = "Rel Ab [%]",
  cluster_columns = FALSE,
  show_row_names = TRUE,
  show_column_names = FALSE,
  column_names_rot = 0,
  column_names_centered = TRUE,
  top_annotation = top_annot,
  col = colorRampPalette(brewer.pal(9, "Blues"))(100),
  # size
  width  = unit(n_cols * cell_w, "inches"),
  height = unit(n_rows * cell_h, "inches"),
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize)
)

# Save images
png("../figures/common_taxa.png", 
    width = n_cols * cell_w + 4,
    height = n_rows * cell_h + 1,
    units = "in", res = 300)
draw(ht)
dev.off()

print(ht)
```