---
title: "ANCOM-BC2 Differential Abundance"
output: html_document
date: "2025-10-23"
---
# Note: run acombc2 with tax_level = "Genus"

# Load Data and
# Identify globally significant taxa
```{r sig}
library(writexl)
library(ComplexHeatmap)
library(grid)

fname <- "../results/ancombc2_genus.rds" 
output <- readRDS(fname)

taxonomy <- get_taxonomy(ps_genus)

# Results by group
res_prim = output$res %>%
  rename(OTU = 1) %>%
  inner_join(taxonomy, by = "OTU") %>%
  dplyr::select(OTU, Genus, everything())

num_sig <- c(
  M   = sum(res_prim$diff_size.nameM & res_prim$passed_ss_size.nameM, na.rm = TRUE),
  L   = sum(res_prim$diff_size.nameL & res_prim$passed_ss_size.nameL, na.rm = TRUE),
  XL  = sum(res_prim$diff_size.nameXL & res_prim$passed_ss_size.nameXL, na.rm = TRUE),
  XXL = sum(res_prim$diff_size.nameXXL & res_prim$passed_ss_size.nameXXL, na.rm = TRUE)
)

all_sig_taxa <- res_prim %>%
  pivot_longer(
    cols = matches("diff_size\\.name|passed_ss_size\\.name"),
    names_to = c(".value","size"),
    names_pattern = "(diff|passed_ss)_size\\.name(.*)"
  ) %>%
  filter(diff & passed_ss) %>%
  pull(Genus) %>%
  unique()

# names of significant taxa
high_ab_taxa <- genus_names[genus_names %in% all_sig_taxa]
low_ab_taxa <- all_sig_taxa[!all_sig_taxa %in% high_ab_taxa]

# --- Write Data to Excel

# Make a single data frame with two columns
taxa_df <- data.frame(
  high_abundance = c(sort(high_ab_taxa), rep(NA, length(low_ab_taxa) - length(high_ab_taxa))),
  low_abundance  = sort(low_ab_taxa)
)

# Write to Excel
write_xlsx(taxa_df, path = "../results/ANCOM_taxa.xlsx")
```

# Subset significant taxa and make a matrix for effect
```{r sig}
process_lfc <- function(df, taxa) {
  df %>%
    filter(Genus %in% taxa) %>%
    mutate(
      M   = ifelse(diff_size.nameM   & passed_ss_size.nameM,   round(lfc_size.nameM, 2), 0),
      L   = ifelse(diff_size.nameL   & passed_ss_size.nameL,   round(lfc_size.nameL, 2), 0),
      XL  = ifelse(diff_size.nameXL  & passed_ss_size.nameXL,  round(lfc_size.nameXL, 2), 0),
      XXL = ifelse(diff_size.nameXXL & passed_ss_size.nameXXL, round(lfc_size.nameXXL, 2), 0)
    ) %>%
    dplyr::select(OTU, Genus, M, L, XL, XXL) %>%
    mutate(
      mean_effect = rowMeans(across(M:XXL, abs), na.rm = TRUE)
    ) %>%
    rename_with(~ paste0(., "-S"), c("M", "L", "XL", "XXL")) %>%
    arrange(desc(mean_effect))
}

# Apply function to high and low abundance taxa
lfc_high <- process_lfc(res_prim, high_ab_taxa)
lfc_low  <- process_lfc(res_prim, low_ab_taxa)

### For plotting
fig_high <- lfc_high %>%
  dplyr::select(-OTU, -mean_effect) %>%
  tibble::column_to_rownames("Genus") %>%
  as.matrix()

fig_low <- lfc_low %>%
  head(30) %>%
  dplyr::select(-OTU, -mean_effect) %>%
  tibble::column_to_rownames("Genus") %>%
  as.matrix()
```

# Separate plots
```{r separate_plots}
# Cell height in inches (adjust as needed)
cell_h <- 0.2
cell_w <- 0.6 # same as cell_h

# Font sizes
row_fontsize <- 10
col_fontsize <- 11

# --- High Ab taxa ---
n_cols <- ncol(fig_high)
n_rows <- nrow(fig_high)

ht_high <- Heatmap(
  fig_high,
  name = "lfc",
  show_row_names = TRUE,
  show_column_names = TRUE,
  cluster_columns = FALSE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE,
  # optional
  width  = unit(n_cols * cell_w, "inches"),
  height = unit(n_rows * cell_h, "inches"),
  column_title = "High Abundance"
)

# Define rowname width in first plot
ht_grob <- draw(ht_high, show_heatmap_legend = FALSE)
ht1 <- ht_grob@ht_list[[1]]
fig_props <- ht1@layout$layout_size

rowname_width_in <- convertWidth(
  fig_props$row_names_right_width,
  "inches", valueOnly = TRUE
)

common_width <- n_cols * cell_w + rowname_width_in + 2 # in


# --- Low Ab taxa ---
n_rows <- nrow(fig_low)

ht_low <- Heatmap(
  fig_low,
  name = "lfc",
  show_row_names = TRUE,
  show_column_names = TRUE,
  cluster_columns = FALSE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE,
  width  = unit(n_cols * cell_w, "inches"),
  height = unit(n_rows * cell_h, "inches"),
  # Use same row name width as high abundance
  row_names_max_width = unit(rowname_width_in, "inches"),
  column_title = "Low Abundance"
)

# Save images
png("../figures/ancom_high_ab.png", 
    width = common_width,
    height = n_rows * cell_h + 1,
    units = "in", res = 300)
draw(ht_high)
dev.off()

png("../figures/ancom_low_ab.png", 
    width = common_width,
    height = n_rows * cell_h + 1,
    units = "in", res = 300)
draw(ht_low)
dev.off()
```
# Combined Heatmaps
```{r heatmap}

# High abundance heatmap
ht_high <- Heatmap(
  fig_high,
  name = "Comp. Ab. > 0.5%",
  show_row_names = TRUE,
  show_column_names = TRUE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE
)

# Low abundance heatmap
ht_low <- Heatmap(
  fig_low,
  name = "Top low ab",
  show_row_names = TRUE,
  show_column_names = TRUE,
  cluster_columns = FALSE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE
)

ht_list <- ht_high %v% ht_low

# Draw combined heatmap
png("../figures/ancom_high_low_ab.png",
    width = 6,  # width in inches; can adjust
    height = 8, # height in inches; can adjust
    units = "in", res = 300)
draw(ht_list)
dev.off()

```

# Bias corrected abundance
```{r bc}
bc_out <- output$bias_correct_log_table
metadata <- get_metadata(ps_genus)

bc_long <- bc_out %>%
  rownames_to_column("OTU") %>%
  pivot_longer(-OTU, names_to = "Sample", values_to = "bc_abund") %>%
  inner_join(taxonomy, by = "OTU") %>%
  inner_join(metadata, by = "Sample") %>%
  dplyr::select(Sample, Genus, bc_abund, size.name, size.mm) 

# can't have boxplot with 3 data points
ggplot(bc_long %>% filter(Genus %in% high_ab_taxa),
       aes(x = size.name, y = bc_abund, color = size.mm)) +
  geom_point() +
  facet_wrap(~ Genus, scales = "free_y") +
  theme_bw() +
  labs(
    x = "Size class",
    y = "Bias-corrected abundance",
    title = "Differential abundance patterns across size classes"
  )

```
