---
title: "child_diff_abundance"
output: html_document
date: "2025-10-23"
---
# Load ALDEx2 data and define clr
```{r load_data}
library(writexl)
library(ComplexHeatmap)
library(grid)

effect_threshold <- 1
p_threshold <- 0.05

fname <- "../results/aldex_t.rds"
res0 <- readRDS(fname) 

# Join taxonomy with aldex results
taxonomy <- get_taxonomy(ps_genus)
res0$res <- map(res0$res, ~ .x %>%
    rownames_to_column("OTU") %>%
    inner_join(taxonomy, by = join_by("OTU")) %>%
    dplyr::select(OTU, Family, Genus, diff.btw, diff.win, effect, wi.eBH)
  ) 

# Define names of significant taxa per comparison and count them
res <- res0 %>%
  mutate(
    sig_taxa = map(res, ~ .x %>%
        filter(wi.eBH < p_threshold & abs(effect) > effect_threshold) %>%
        pull(Genus) 
    ),
    # add column for number of significant taxa
    n_sig = map_dbl(sig_taxa, length)
  )

# names of significant taxa
all_sig_taxa <- unique(unlist(res$sig_taxa))
high_ab_taxa <- genus_names[genus_names %in% all_sig_taxa]
low_ab_taxa <- all_sig_taxa[!all_sig_taxa %in% high_ab_taxa]

# Make a single data frame with two columns
taxa_df <- data.frame(
  high_abundance = c(sort(high_ab_taxa), rep(NA, length(low_ab_taxa) - length(high_ab_taxa))),
  low_abundance  = sort(low_ab_taxa)
)

# Write to Excel
write_xlsx(taxa_df, path = "../results/ALDEx2_taxa.xlsx")
```

# Subset significant taxa and make a matrix for effect
```{r sig}
process_clr <- function(df, taxa, p_threshold, effect_threshold) {
  # Combine into wide format
  map2(df$res, df$comparison, ~ .x %>%
    filter(Genus %in% taxa) %>%
    mutate(
      effect_update = ifelse(wi.eBH < p_threshold & abs(effect) > effect_threshold, effect, 0)
    ) %>%
    dplyr::select(OTU, Family, Genus, effect_update) %>%
    rename(!! as.character(.y) := effect_update) 
  ) %>%
  reduce(full_join, by = c("OTU", "Family", "Genus")) %>%
  mutate(
    mean_effect = rowMeans(across(all_of(res$comparison), abs), na.rm = TRUE)
  ) %>%
  arrange(desc(mean_effect))
}

# Apply function to high and low abundance taxa
effect_high <- process_clr(res, high_ab_taxa, p_threshold, effect_threshold)
effect_low  <- process_clr(res, low_ab_taxa, p_threshold, effect_threshold)

### For plotting
fig_high <- effect_high %>%
  dplyr::select(-OTU, -Family, -mean_effect) %>%
  tibble::column_to_rownames("Genus") %>%
  as.matrix()

fig_low <- effect_low %>%
  head(30) %>%
  dplyr::select(-OTU, -Family, -mean_effect) %>%
  tibble::column_to_rownames("Genus") %>%
  as.matrix()
```

# Separate Heatmaps

```{r low_ab}

# Cell height in inches (adjust as needed)
cell_h <- 0.2
cell_w <- 0.6 # same as cell_h

# Font sizes
row_fontsize <- 10
col_fontsize <- 11

# --- High Ab taxa ---
n_cols <- ncol(fig_high)
n_rows <- nrow(fig_high)

ht_high <- Heatmap(
  fig_high,
  name = "effect",
  show_row_names = TRUE,
  show_column_names = TRUE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE,
  width  = unit(n_cols * cell_w, "inches"),
  height = unit(n_rows * cell_h, "inches"),
  column_title = "High Abundance"
)

# Define rowname width in first plot
ht_grob <- draw(ht_high, show_heatmap_legend = FALSE)
ht1 <- ht_grob@ht_list[[1]]
fig_props <- ht1@layout$layout_size

rowname_width_in <- convertWidth(
  fig_props$row_names_right_width,
  "inches", valueOnly = TRUE
)

common_width <- n_cols * cell_w + rowname_width_in + 2 # in


# --- Low Ab taxa ---
n_rows <- nrow(fig_low)

ht_low <- Heatmap(
  fig_low,
  name = "effect",
  show_row_names = TRUE,
  show_column_names = TRUE,
  cluster_columns = FALSE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE,
  width  = unit(n_cols * cell_w, "inches"),
  height = unit(n_rows * cell_h, "inches"),
  # Use same row name width as high abundance
  row_names_max_width = unit(rowname_width_in, "inches"),
  column_title = "Low Abundance"
)

# Save images
png("../figures/aldex_high_ab.png", 
    width = common_width,
    height = n_rows * cell_h + 1,
    units = "in", res = 300)
draw(ht_high)
dev.off()

png("../figures/aldex_low_ab.png", 
    width = common_width,
    height = n_rows * cell_h + 1,
    units = "in", res = 300)
draw(ht_low)
dev.off()


```
# Combined Heatmaps
```{r heatmap}

# High abundance heatmap
ht_high <- Heatmap(
  fig_high,
  name = "High Ab\neffect",
  show_row_names = TRUE,
  show_column_names = TRUE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE
)

# Low abundance heatmap
ht_low <- Heatmap(
  fig_low,
  name = "Low Ab\neffect",
  show_row_names = TRUE,
  show_column_names = TRUE,
  cluster_columns = FALSE,
  row_names_gp = gpar(fontsize = row_fontsize),
  column_names_gp = gpar(fontsize = col_fontsize),
  column_names_rot = 0,
  column_names_centered = TRUE
)

ht_list <- ht_high %v% ht_low

# Draw combined heatmap
png("../figures/aldex_high_low_ab.png",
    width = 6,  # width in inches; can adjust
    height = 8, # height in inches; can adjust
    units = "in", res = 300)
draw(ht_list)
dev.off()

```
